version: "3.5"

services:
  matjrah:
    env_file: .env
    container_name: ${APP_CONTAINER_NAME}
    build: .
    volumes:
      - ./core:/var/www
    working_dir: /var/www
    networks:
      - ouredu-service-app

  matjrah-nginx:
    env_file: .env
    container_name: ${APP_NGINX_CONTAINER_NAME}
    build: ./.docker/nginx
    restart: always
    ports:
      - "${APP_NGINX_PORT}:80"
    volumes:
      - ./core:/var/www
    depends_on:
      - matjrah
    networks:
      ouredu-service-app:
        aliases:
          - matjrah-nginx

networks:
  ouredu-service-app:
    name: ${OUR_EDU_NETWORK_NAME}
    external: true
    driver: bridge
